### ISSUE TITLE
Investigate and implement solution for third-party dependencies

### ISSUE THREAD

**Issue by Tooa** [tudarmstadt-lt/DIVID-DJ#2]
See discussion in #1.

**Comment by seyyaw** [comment]
I opt for artifactory. Long last solution to LT also.

**Comment by Tooa** [comment]
We still have to check if `Artifactory` works with Travis. Are we talking about this [solution](https://www.jfrog.com/)?

BTW, the solution to use a snapshot repository on GitHub will not work, because GitHub has a 100 MB file limit and the NER tagger is around 200 MB.

**Comment by seyyaw** [comment]
yes I was to mean [jfrog](https://www.jfrog.com/)

**Comment by alexanderpanchenko** [comment]
@seyyaw do you mean that we used it before? do you need to pay for it? can we deploy on our new web server? 

@Tooa good point. this is very hacky solution anyway :-)

**Comment by alexanderpanchenko** [comment]
@Tooa good point. this is very hacky solution anyway :-)

**Comment by seyyaw** [comment]
I mean Installing Artifactory to our webserver hence any non-public dependencies can be easily shared among local developers.

**Comment by alexanderpanchenko** [comment]
right, shall we buy a license? can you investigate pricing and ease of use?
