### ISSUE TITLE
Find a solution for integration of Github issues with an agile board

### ISSUE THREAD

**Issue by alexanderpanchenko** [tudarmstadt-lt/DIVID-DJ#3]
Post ideas here e.g.:
- trello (supports integration?) http://blog.trello.com/github-and-trello-integrate-your-commits/
- https://www.zenhub.io/ 
- https://github.com/wooga/gitthello

**Comment by alexanderpanchenko** [comment]
the zenhub looks like what we need. any comments? can you try it?

![screen shot 2015-11-06 at 16 20 38](https://cloud.githubusercontent.com/assets/1456830/11000487/60eeda18-84a2-11e5-8b2f-4523163e723d.png)

"If you're building open source software, ZenHub is 100% free. If you're a student at any accredited institution, ZenHub is 100% free for you too! Just install the extension, and sign in via GitHub."

**Comment by alexanderpanchenko** [comment]
"If you're building open source software, ZenHub is 100% free. If you're a student at any accredited institution, ZenHub is 100% free for you too! Just install the extension, and sign in via GitHub."

**Comment by Tooa** [comment]
I would also go with ZenHub. It's the only solution that is highly integrated with Github and don't need external Websites/Tools.

**Comment by seyyaw** [comment]
Yes but we should create two LT orgs, I think. One for open source and one for Private.

**Comment by alexanderpanchenko** [comment]
@seyyaw why. we already have private repos in our organisation.

**Comment by seyyaw** [comment]
I don't know if you have the same message but for me I have the following (as we have some private projects in the organization)
![zenhub-lt-trail-message](https://cloud.githubusercontent.com/assets/1056051/11021097/5f62a6ac-8637-11e5-8920-699dfd70ad38.png)
